name: Python application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with ruff
      run: |
        pip install ruff
        # stop the build if there are Python syntax errors or undefined names
        ruff --select=E9,F63,F7,F82 --show-source .
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        ruff --exit-zero -line-length=127 --statistics --target-version=py37
    - name: Test with pytest
      env:
        robin_username: ${{ secrets.username }}
        robin_password: ${{ secrets.password }}
        robin_mfa: ${{ secrets.mfa }}
        account_number: ${{ secrets.account }}
        zipcode: ${{ secrets.zipcode }}
        crypto_account: ${{ secrets.crypto }}
        gemini_account_key: ${{ secrets.gemini_account_key }}
        gemini_account_secret: ${{ secrets.gemini_account_secret }}
        gemini_sandbox_key: ${{ secrets.gemini_sandbox_key }}
        gemini_sandbox_secret: ${{ secrets.gemini_sandbox_secret }}
        tda_encryption_passcode: ${{ secrets.tda_encryption_passcode }}
        tda_order_account: ${{ secrets.tda_order_account }}
      run: |
        pip install pytest pytest-dotenv python-dateutil
        pytest
